### PR TITLE
Feature: Add expat component

### PR DESCRIPTION
**Pull request by mahavirj**
This component is pretty independent and good candidate for component manager.

### CODE REVIEW

**Review by tore-espressif — CHANGES_REQUESTED** [review]
Could you please update file https://github.com/espressif/idf-extra-components/blob/master/test_app/CMakeLists.txt ? Something like this

```
set(EXTRA_COMPONENT_DIRS "../libsodium ../expat")

# Set the components to include the tests for.
set(TEST_COMPONENTS libsodium expat CACHE STRING "List of components to test")
```

We don't run these tests anywhere yet, they are only built.

I guess that the test build will fail because it is set for idf v4.3, so I'll fix it later

**Comment by mahavirj** [comment]
@tore-espressif Added entry for this component to `test_app`. Also added partition table for increased firmware size and verified `expat` tests locally.

**Comment by tore-espressif** [comment]
@mahavirj LGTM, thank you.
Do you want anybody else to review, or can I merge it now?

**Comment by mahavirj** [comment]
> LGTM, thank you.

Thanks for approving, I will go ahead and merge it.

**Pull request merged**
