### PR TITLE
sh2lib: Bump version to 1.0.1

### PR DESCRIPTION
**Pull request by AdityaHPatwardhan**
Changes:
1) Enabled support for esp_crt_bundle with esp_tls.

### CODE REVIEW

**Comment by mahavirj** [comment]
@AdityaHPatwardhan Please see pre-commit failures here. Otherwise LGTM

**Comment by mahavirj** [comment]
@tore-espressif Can you please check CI failures here?

**Comment by tore-espressif** [comment]
@mahavirj This is not caused by current changes. Nightly builds started failing after https://github.com/espressif/idf-extra-components/pull/43 .  @AdityaHPatwardhan could you please revert https://github.com/espressif/idf-extra-components/pull/43 and push?

**Comment by tore-espressif** [comment]
More details: For some reason idf4.3 has newer version of git than 4.4 and latest. Probably connected to this https://github.blog/2022-04-12-git-security-vulnerability-announced/

**Comment by mahavirj** [comment]
Going ahead with merge here. We can fix CI problem in separate PR.

**Pull request merged**
