### PR TITLE
usb msc host: remove unused variable lun

### PR DESCRIPTION
**Pull request by esp-saurabhbansal**
1. remove unused variable 'lun'
2. usb composite device (msc + cdc) verified for its working.

### CODE REVIEW

**Comment by esp-saurabhbansal** [comment]
@tore-espressif @roma-jam @Dazza0 
This PR is for supporting composite msc devices.
The MR for corresponding IDF example that can be used for checking composite device is raised [here](https://gitlab.espressif.cn:6688/espressif/esp-idf/-/merge_requests/23135)

The composite device feature can be tested using 2 ESP chips with following scenarios:
1. One ESP chip acts as usb msc host (example [this](https://github.com/espressif/esp-idf/tree/master/examples/peripherals/usb/host/msc)). Other ESP chip acts as USB Composite device (example [this](https://gitlab.espressif.cn:6688/espressif/esp-idf/-/merge_requests/23135))
2. One ESP chip acts as usb cdc host (example [this](https://github.com/espressif/esp-idf/tree/master/examples/peripherals/usb/host/cdc/cdc_acm_host)). Other ESP chip acts as USB Composite device (example [this](https://gitlab.espressif.cn:6688/espressif/esp-idf/-/merge_requests/23135))

**Review by tore-espressif — CHANGES_REQUESTED** [review]
Thanks you @esp-saurabhbansal ! Could you please update the related sections of README.md?

**Comment by esp-saurabhbansal** [comment]
> Thanks you @esp-saurabhbansal ! Could you please update the related sections of README.md, too?

Thanks @tore-espressif.
README.md is modified.

**Review by tore-espressif — APPROVED** [review]

**Comment by tore-espressif** [comment]
Related https://github.com/espressif/esp-idf/issues/10443

**Pull request merged**
