### PR TITLE
fix(esp_encrypted_img): correct the dependency for generating encrypted image

### PR DESCRIPTION
**Pull request by mahavirj**
Closes https://github.com/espressif/idf-extra-components/issues/349

# Checklist

- [X] CI passing

# Change description
_Please describe your change here_

### CODE REVIEW

**Comment by bonnee** [comment]
While you're there, it would be more versatile to have the function create a dynamic target name (e.g. based on input/output file name).
This will enable the possibility to call the function on multiple files (in my use case I need to encrypt multiple partitions)

**Comment by mahavirj** [comment]
@bonnee 

I didn't quite get your requirement, can you please share more information, any pointers to your use-case? Interim, the existing target is used from ESP-IDF example as well, so we can keep that same and maybe consider making provision for new one.

**Comment by bonnee** [comment]
Okay, so I have a project that makes use of a spiffs partition. I want to encrypt both the firmware partition and the spiffs in order to securely flash them on my esp32. With the current function I cannot do that as there would be a duplicate target name. I recreated the function by changing `add_custom_target(encrypt_bin_target, ...` with
```
get_filename_component(name ${tar_file} NAME)
set(target_name archive_${name}_target)
add_custom_target(${target_name}, ...
```
This will create (almost) unique targets for each call and solve my use case.

**Comment by mahavirj** [comment]
@bonnee 

>  I want to encrypt both the firmware partition and the spiffs in order to securely flash them on my esp32.

Just to clarify the pre encrypted OTA scheme only ensures confidentiality over network transport and as such its not related to flash encryption. Please refer this guide: https://docs.espressif.com/projects/esp-idf/en/latest/esp32c3/api-reference/system/esp_https_ota.html#ota-upgrades-with-pre-encrypted-firmware.

**Comment by bonnee** [comment]
Yes I am aware of that. I want to encrypt images in order to send them securely over unsecure channels

**Comment by hmalpani** [comment]
@bonnee 
The script `esp_enc_img_gen.py` present in [tools/](https://github.com/espressif/idf-extra-components/tree/master/esp_encrypted_img/tools) can be used to create the encrypted image for the spiffs partition.

**Review by hmalpani — APPROVED** [review]
I tested the changes and was able to create the encrypted binary for both the application and the spiffs binary. LGTM

**Pull request merged**
